ENV: develop
HOST_IP: 127.0.0.1
DB_DRIVER: postgres
DB_CONNECTION_STRING: postgresql://postgres:root@127.0.0.1:5433/postgis_db?sslmode=disable
MIGRATION_URL: file://db/migration
PORT: 8081
SERVICE_NAME: polygon
